### ISSUE TITLE
Add switch to use non-interactively.

### ISSUE THREAD

**Issue by josdotso** [jeaye/nixos-in-place#10]
Something like 'yum -y install' where -y is accepting defaults.

**Comment by jeaye** [comment]
This script relies on the user's input for a couple of prompts:

1. Initial "is this good?" check before starting (asks for y or n)
2. Root password prompt of the new machine (as prompted by passwd; part of nixos, not this script)
3. Final prompt to reboot immediately (asks for y or n)

1 and 3 are easy to do non-interactively, but 2 is not. Are you only looking to quiet 1 and 3, or all of them?

**Comment by josdotso** [comment]
Didn't think about 2.  Hmm.. An environment variable for that would be cool.  However, with the passwd being part of NixOS the only way to seed it would be to pipe an echo of the $PASS into the call to NixOS... And that probably wouldn't work either.  Can you link to the script source for the NixOS side.  Is this the call on the nixos-in-place side?
https://github.com/jeaye/nixos-in-place/blob/master/stage1#L48

Thanks!

**Comment by jeaye** [comment]
https://github.com/jeaye/nixos-in-place/blob/master/stage2#L82 That's the line which installs NixOS; as part of nixos-install, the user is presented with the password prompt.

**Comment by josdotso** [comment]
I see.  Yeah.  This probably won't work then. Thanks anyway.  Feel free to close this ticket.

I think this is where passwd is called by nixos-install:

https://github.com/NixOS/nixpkgs/blob/a4f5dc8bbf5435dd7bfb1bb6c36c28c6ce775dd3/nixos/modules/installer/tools/nixos-install.sh#L260

**Comment by jeaye** [comment]
Thanks for looking into it and reporting back.
