### ISSUE TITLE
Network not properly configured on digital ocean.

### ISSUE THREAD

**Issue by kevincox** [jeaye/nixos-in-place#15]
I started a new Digital Ocean VPS with Ubuntu 15.10 and ran `./install` From the latest git (c85487eb58b7b3dbbf3cf242bc09d00c888e9257) and when the droplet rebooted it had no network connection. (Pinging IPs didn't work).

To fix it I had to add the correct IP address to `enp0s3`, remove the incorrect one (`169.254.115.80`) and set the default gateway.

The files in `/old-root/etc/network` provided the correct information.

**Comment by jeaye** [comment]
I believe all you needed to do was run the `/etc/nixos-in-place/setup-network` script and it'd do this for you. It's set to be a systemd target, but there are a few scenarios where it doesn't run and it's meant to; that's a separate issue. Are you able to verify with me that the `setup-network` script would do what you need?

If you can, then we can close this and just deal with the fact that it doesn't always run when it should.

**Comment by kevincox** [comment]
I don't know if I am doing something wrong but I don't have a `/etc/nixos-in-place` directory on the new system. I tried running the `setup-network` script from the repo but it fails because it looks in `/etc/network` which doesn't exist on the nixos system.

**Comment by kevincox** [comment]
Oh, it's my fault. I didn't understand that I needed to specify the `-d` flag. I find that sentence a little confusing, maybe it could be reworded.
