### ISSUE TITLE
setup-network DigitalOcean woes.

### ISSUE THREAD

**Issue by kevincox** [jeaye/nixos-in-place#18]
Hello again, I was trying to set up a digital ocean droplet from Ubuntu 15.10 and am having troubles with networking.

- The `/etc/nixos-in-place/setup-network` script appears to have been run by systemd but didn't work (maybe it should be `After=network.target`?).
- Running the script manually works for IPv4 nodes.
- The script fails on IPv6 nodes (not even the IPv4 parts work).

The commands I am using to test:

```
# apt-get update && apt-get install -y squashfs-tools git
# git clone https://github.com/kevincox/nixos-in-place -b patch-2
# cd nixos-in-place
# ./install.sh -d
>>> Checking environment... seems sane
>>> NixOS installer (nixos-in-place)
>>>    GRUB => /dev/vda
>>>    Root => /dev/vda1 (ext4)
>>>    ISO => latest-iso-minimal-x86_64-linux
>>>    Digital Ocean => true
>>>    Working directory => /tmp/tmp.KIWITgncGa
>>> Continue? [yn] y
...
```

**Comment by jeaye** [comment]
The script doesn't currently support IPv6; I'm glad it works for IPv4, as intended, and there are issues with it not always working when it's executed by systemd. If you know the cause of this, do try out a fix and let me know.

**Comment by kevincox** [comment]
Will do. TBH I am probably going to drop DO because of things like this but if I do end up debugging this I will be sure to submit patches for future users.
