### ISSUE TITLE
Issue on digital ocean.

### ISSUE THREAD

**Issue by ibrahimsag** [jeaye/nixos-in-place#21]
I get this error while trying to use with a digital ocean droplet with ubuntu and debian images. any help is appreciated.

```
unshare: cannot change root filesystem propagation: Invalid argument
```

**Comment by jeaye** [comment]
1. Which version of Ubuntu and Debian did you try?
2. Were you using LVM?
3. Encryption?
4. Any other info on your droplet?

**Comment by ibrahimsag** [comment]
i tried with bunch of versions of both images. other than that, i activated ipv6 and selected an ssh key. nothing else was used.

**Comment by ibrahimsag** [comment]
https://github.com/elitak/nixos-infect works for fedora images. just FYI.

**Comment by jeaye** [comment]
@ibrahimsag Ah, IPv6 is likely to not work, but I don't think this is the issue that would arise. It could be that DO has changed something recently; I'll try to look at it this weekend. If you can offer more information (try running with script with `bash -x`), that'd be lovely.

**Comment by cleverca22** [comment]
see also: https://github.com/NixOS/nixops/issues/605
