### ISSUE TITLE
DigitalOcean now uses /dev/vda

### ISSUE THREAD

**Issue by wmhilton** [jeaye/nixos-in-place#23]
`/root/nixos-in-place/util: line 23: grub_device: unbound variable`

Since line 23 is before the help message, event `./install -h` just results in the above crash.

Resolved by adding a third check (`elif grep '/dev/vd'`) and suggest a final `else` clause aborting with a helpful message if `$grub_device` can't be inferred. 

Details:
DigitalOcean
Debian 5.5
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)

**Comment by jeaye** [comment]
Thanks for reporting this! Are you interested in submitting a PR for that change?

**Comment by wmhilton** [comment]
Resolved in pull request https://github.com/jeaye/nixos-in-place/pull/24
