### ISSUE TITLE
Iso download: unverified, not trustworthy host, not overrideable

### ISSUE THREAD

**Issue by Rotsor** [jeaye/nixos-in-place#31]
This will be subsumed by https://github.com/jeaye/nixos-in-place/issues/9 if that's ever done, but before it's done:

- Iso download is unverified: if it gets corrupted or replaced by the owner of d3g5gsiof5omrk.cloudfront.net then the script won't notice.
- Iso is downloaded every time and there is no configuration option to use a previously downloaded one, which is a pain if something goes wrong and you have to re-run the script.

**Comment by jeaye** [comment]
No doubt, you're right. This is due to the unfortunate change of NixOS no longer hosting their own ISOs. The relevant commit for that is here: https://github.com/jeaye/nixos-in-place/commit/eb876b7b6ccc2a84b353ad232bcf935eb0b6c9e7

Preferably, there's a more trusted source for this, like there used to be. Looking at the NixOS download page again ( http://nixos.org/nixos/download.html ), it seems like there are two immediately possible steps for improvement.

1. Check the SHA256 which NixOS is kind enough to put adjacent to each ISO on cloudfront
2. Look for the ISO before downloading and skip the download if the checksum matches
3. Crawl the NixOS download page for the link and checksum each time instead

The first two are straightforward and sane. If you have other ideas as to how this setup can be improved, let me know.

**Comment by jeaye** [comment]
After a second glance, I'm using `wget -c`, which should continue any incomplete downloads. An example: https://gist.github.com/jeaye/b30d2bffe982ca54e3ba6946636a1e25

With that said, checksum validation will certainly help.

**Comment by Rotsor** [comment]
`wget -c` doesn't help now because we're downloading to a new temporary directory every time.

**Comment by jeaye** [comment]
Right, that's what the `-w` flag is for. You can enter one of the previous working directories and hopefully resume where you left off.

**Comment by Rotsor** [comment]
Oh, I see! I didn't notice this option. Maybe it's good enough. 

Re-using the working directory didn't even occur to me because I was expecting it to be in a bad state after a failed install.

**Comment by jeaye** [comment]
On Sun, Feb 19, 2017 at 11:27:17AM -0800, Rotsor wrote:
> Re-using the working directory didn't even occur to me because I was expecting it to be in a bad state after a failed install.

Depending how far you made it, it _probably_ is. That's the main reason for doing everything in a temporary directory, with a clean slate each time. I think users of nixos-in-place should ideally only have to run it once. Developers who're tinkering, like you or me, may want to reuse working directories. What I typically do is just comment out the line which downloads the ISO and add a line which copies it from ~ or similar.

I'm not yet convinced that the typical user should care about this. With that said, I've made a patch for checksum validation, which I'll push very soon.

**Comment by Rotsor** [comment]
That makes sense. Thanks.

**Comment by jeaye** [comment]
Pushed the checksum validation. https://github.com/jeaye/nixos-in-place/commit/1d512bc6d7e8345cfacae7db89e79033f4d6a0e7

**Comment by Rotsor** [comment]
Shouldn't sha256 be hard-coded? Otherwise we're still exposed to whoever owns d3g5gsiof5omrk.

Your commit reminds me: rm -f ./$iso means that it's basically impossible to benefit from -c in `wget -c`, even if you re-use the working directory.

**Comment by jeaye** [comment]
> Shouldn't sha256 be hard-coded? Otherwise we're still exposed to whoever owns d3g5gsiof5omrk.

You make a fair point. I can hard-code it.

> Your commit reminds me: rm -f ./$iso means that it's basically impossible to benefit from -c in `wget -c`, even if you re-use the working directory.

Another fair point. The rm can likely just be removed.

**Comment by jeaye** [comment]
The former was resolved with https://github.com/jeaye/nixos-in-place/commit/75d08ea06c2c704242d4870e71fe30ee2abb845c last week and the latter has been resolved with https://github.com/jeaye/nixos-in-place/commit/ded521d334f0df7a4152d312c4fd7e4faa09522a just now. :)

**Comment by Rotsor** [comment]
Thanks!
