### ISSUE TITLE
grub-install: error: will not proceed with blocklists

### ISSUE THREAD

**Issue by tinco** [jeaye/nixos-in-place#4]
Hi,

Last week I used nixos-in-place to install NixOS on a Digital Ocean machine, and it went perfectly. I thought I'd write up a blog on how to do it and why, so I spun up a new Digital Ocean node and tried it again but now it fails with a grub2 error. This is the full log if you need it, I start from a 1GB 64-bit Ubuntu 14.04 node in the AMS datacenter:

```
installing the GRUB 2 boot loader on /dev/vda...
Installing for i386-pc platform.
/nix/store/6czhmdkzs04y1bdlq53yvw6hn1bvl1zr-grub-2.x-2015-07-27/sbin/grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
/nix/store/6czhmdkzs04y1bdlq53yvw6hn1bvl1zr-grub-2.x-2015-07-27/sbin/grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
/nix/store/6czhmdkzs04y1bdlq53yvw6hn1bvl1zr-grub-2.x-2015-07-27/sbin/grub-install: error: will not proceed with blocklists.
/nix/store/w345fzhsr2ckzhazmxr3lc906glnxqiy-install-grub.pl: installation of GRUB on /dev/vda failed
```

Thanks a lot for the tool, I'm having a lot of fun using NixOS on Digital Ocean so hopefully we can get it working again.

**Comment by tinco** [comment]
Never mind! I found the difference. I accidentily selected Ubuntu 14.04 instead of 15.10. On 15.10 everything works perfect! No idea what exactly changed but good to know :)

**Comment by jeaye** [comment]
\o/ Thanks for following up; I'm excited to read the blog post. Shoot me over a link when it's done, if you don't mind.

**Comment by tinco** [comment]
I've got the basic idea of it done, I wanted to finish it today but had a lot of administration to do so perhaps tomorrow.

https://github.com/tinco/blog.tinco.nl/blob/master/_posts/2016-01-31-nixos-on-digital-ocean.md

**Comment by jeaye** [comment]
Neat! Thanks for the writeup; it'll be good to see it published and maybe even on HN. It's interesting that you're delving into a post about the Wayland source. That's something that would also be a good read, once finished.

**Comment by tinco** [comment]
Thanks for the kind words, I'll try and pick up the wayland post some day as well. I started because I felt reading about codebases is fun and I didn't see many other blogs do that so maybe I'd spark a trend for it. I'm not a very good writer though so I got a bit discouraged :)
