### ISSUE TITLE
download link seems offline

### ISSUE THREAD

**Issue by nerdbude** [jeaye/nixos-in-place#51]
I try to install NixOS on Hetzner Cloud with nixos-in-place. 
The process stops with: 
`wget: unable to resolve host adress 'd3g5gsiof5omrk.cloudfront.net'`
Is there a solution for this?

**Comment by zergaloid** [comment]
Yes, it is offline
Replacing values with ones from the [NixOS download buttons](https://releases.nixos.org/nixos/22.11/nixos-22.11.550.660e7737851/nixos-minimal-22.11.550.660e7737851-x86_64-linux.iso.sha256) seems to work

Just go into the install script and change `primary_version`, `secondary_version` and `minimal_checksum` (here I am assuming you are looking for a no-GUI system) starting at line 50

Then replace `url` on line 151 with ` https://releases.nixos.org/nixos/$primary_version/nixos-$full_version`

**Comment by zergaloid** [comment]
I should probably make a pull request with this fix
